def going_to_gym():
    print("Ate Boiled eggs")
    print("wearing the shoes")
    print("walking to the gym")
    print("Working out")
def study_plan():
    print("making notes")
    print("Watching the baraa videos in YT")
    print("practice linux")
    print("applying for the jobs")
    print("Practicing the python")
def diet_plan():
    print("2 bananas")
    print("1 scoop of whey protien")
    print("No sugars")
    print("Balck coffe only")
    print("5 eggs")
def sleep_plan():
    print("Have a good 10 hours of sleep")

print("daily routine")
print("Day->>>>>>>>>>>>>>>>>>>>1")
going_to_gym()
study_plan()
diet_plan()
sleep_plan()
print("Day->>>>>>>>>>>>>>>>>>>2")
going_to_gym()
study_plan()
diet_plan()
sleep_plan()
print("Day->>>>>>>>>>>>>>>>>>>3")
going_to_gym()
study_plan()
diet_plan()
sleep_plan()